#!/usr/bin/env python3
"""cut_revision.py — cut a coordinated cross-block chip revision.

A revision pins EVERY block at once (the monorepo makes this atomic — one tag). This tool gathers
the ground-truth state and emits the docs/REVISIONS.md manifest entry, then (with --tag) creates the
annotated git tag. See docs/REVISION_SYNC_SOP.md §1, §4.

Default is DRY-RUN: it prints the manifest block and the exact git command it *would* run, and
touches nothing. Pass --write to append to docs/REVISIONS.md and --tag to create the annotated tag.

Usage:
  python3 scripts/cut_revision.py R1   --milestone "Proxy-PDK block baseline"      # dry-run preview
  python3 scripts/cut_revision.py R1.5 --milestone "Full-chip GF180 assembly" --write --tag

Rev name must be R<N> (baseline, immutable) or R<N>.5 (assembly). Stdlib only.
"""
from __future__ import annotations
import argparse
import re
import subprocess
import sys
from pathlib import Path

# reuse the ground-truth classifier
sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_progress as gp  # noqa: E402

ROOT = gp.ROOT
REVFILE = ROOT / "docs" / "REVISIONS.md"
REV_RE = re.compile(r"^R([1-9]\d*)(\.5)?$")
BLOCK_ISA = {  # latest ISA version per block (docs/isa/) — mate/vecu have none
    "kve": "kv-isa-0.2", "tiu": "tiu-isa-0.1", "acu/mate": "—",
    "acu/vecu": "—", "acu/precision_controller": "pc-isa-0.2", "chip": "lh-isa-0.1 (unified)",
}


def git(*args: str) -> str:
    return subprocess.check_output(["git", "-C", str(ROOT), *args], text=True).strip()


def block_sha(block: str) -> str:
    return git("log", "-1", "--format=%h", "--", gp.bpath(block))


def arch_version() -> str:
    for line in (ROOT / "arch.yml").read_text().splitlines():
        m = re.match(r"\s*version:\s*(\S+)", line)
        if m:
            return m.group(1)
    return "?"


def signoff_summary(block: str) -> str:
    """Condense the block's macro×PDK sign-off states into one manifest cell."""
    rows = gp.scan_block(block)
    from collections import defaultdict
    by_status = defaultdict(list)
    for r in rows:
        by_status[r["status"]].append(f'{r["macro"]}@{r["pdk"]}')
    parts = []
    for status in ("signed-off", "route-clean", "caveated", "prose-only", "no-gds", "config-only"):
        if by_status.get(status):
            parts.append(f'**{status}**: ' + ", ".join(sorted(by_status[status])))
    return "; ".join(parts) if parts else "—"


def build_entry(rev: str, milestone: str) -> str:
    head = git("rev-parse", "HEAD")
    head_short = git("rev-parse", "--short", "HEAD")
    date = git("log", "-1", "--format=%cs")
    kind = "assembly" if rev.endswith(".5") else "baseline (frozen)"
    lines = [
        f"## {rev} — {milestone}",
        "",
        f"- **Tag:** `rev-{rev}` · **Kind:** {kind}",
        f"- **Date:** {date} · **Monorepo anchor:** `{head_short}` (`{head}`)",
        f"- **arch.yml doc version:** `{arch_version()}`",
        f"- **Milestone:** {milestone}",
        "",
        "| Block | SHA | ISA | Sign-off summary |",
        "|---|---|---|---|",
    ]
    for block in gp.BLOCKS:
        lines.append(f"| `{block}` | `{block_sha(block)}` | `{BLOCK_ISA.get(block,'—')}` | "
                     f"{signoff_summary(block)} |")
    lines += ["", f"_Generated by scripts/cut_revision.py from ground-truth artifacts._", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("rev", help="revision name: R1, R2, ... (baseline) or R1.5 (assembly)")
    ap.add_argument("--milestone", required=True, help="one-line milestone description")
    ap.add_argument("--write", action="store_true", help="append entry to docs/REVISIONS.md")
    ap.add_argument("--tag", action="store_true", help="create annotated git tag rev-<rev>")
    args = ap.parse_args()

    if not REV_RE.match(args.rev):
        sys.stderr.write(f"bad revision name '{args.rev}' — must be R<N> or R<N>.5\n")
        return 2

    # guardrail: never move an existing baseline tag
    existing = git("tag").split()
    tag = f"rev-{args.rev}"
    if tag in existing:
        sys.stderr.write(f"tag {tag} already exists — baselines are immutable (SOP §4). "
                         f"Cut the next revision instead.\n")
        return 3
    if git("status", "--porcelain"):
        sys.stderr.write("working tree not clean — commit or stash before cutting a revision.\n")
        return 4

    entry = build_entry(args.rev, args.milestone)
    print("=" * 72)
    print(entry)
    print("=" * 72)

    if args.write:
        REVFILE.write_text(REVFILE.read_text().rstrip() + "\n\n---\n\n" + entry)
        print(f"appended entry to {REVFILE.relative_to(ROOT)}")
    else:
        print(f"(dry-run: not written — pass --write to append to {REVFILE.relative_to(ROOT)})")

    if args.tag:
        subprocess.check_call(["git", "-C", str(ROOT), "tag", "-a", tag, "-m",
                               f"{args.rev}: {args.milestone}"])
        print(f"created annotated tag {tag} — push with: git push origin {tag}")
    else:
        print(f"(dry-run: no tag — would run: git tag -a {tag} -m \"{args.rev}: {args.milestone}\")")
    return 0


if __name__ == "__main__":
    sys.exit(main())
